# Generated by Django 5.1.5 on 2025-02-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_description_alter_task_title_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
