# Generated by Django 5.1.7 on 2025-04-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip_addr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='port',
        ),
    ]
